use vms

diff --git a/.github/workflows/raspberry_pi.yml b/.github/workflows/raspberry_pi.yml
--- a/.github/workflows/raspberry_pi.yml
+++ b/.github/workflows/raspberry_pi.yml
@@ -1,5 +1,5 @@
-name: Raspberry Pi
-'on':
+name: Aarch64 Linux Musl
+on:
   workflow_dispatch:
     inputs:
       extra_resolve_options:
@@ -12,16 +12,64 @@ name: Raspberry Pi
     - master
   pull_request:
 jobs:
-  RaspberryPi:
-    uses: steinwurf/cross-compile-action/.github/workflows/action.yml@6.0.0
-    with:
-      extra_resolve_options: ${{ github.event.inputs.extra_resolve_options }}
-      name: Raspberry Pi
-      cxx_mkspec: cxx_raspberry_gxx83_armv7
-      image: ghcr.io/steinwurf/gcc-8.3.0-raspberrypi-armv7:1.0.0
-      test_runner: raspberry_pi
-      test_binary_name: abacus_tests
-      test_binary_directory: build/cxx_raspberry_gxx83_armv7
+  cross-compile:
+    timeout-minutes: 45
+    strategy:
+      fail-fast: false
+    runs-on: [self-hosted, vm, ubuntu-current]
+    name: Raspberry Pi Cross-compile
+    steps:
+      - name: Ensure correct owner of repository
+        run: sudo chown -R actions-runner:actions-runner .
+      - name: Checkout source code
+        uses: actions/checkout@v4
+      - name: Clone toolchains
+        run: rm -rf ~/toolchains && git clone --depth 1 git@github.com:steinwurf/cmake-toolchains.git ~/toolchains
+      - name: CMake Cleanup
+        run: cmake -E remove_directory cmake_build
+      - name: CMake Configure
+        uses: nick-fields/retry@v3
+        with:
+          max_attempts: 3
+          timeout_minutes: 15
+          command: cmake -B cmake_build -DSTEINWURF_RESOLVE_OPTIONS="--git_protocol=git@ $EXTRA_RESOLVE_OPTIONS" -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_BUILD_TYPE=WurfRelease -DCMAKE_TOOLCHAIN_FILE=~/toolchains/zig-toolchain-aarch64-linux-musl.cmake -GNinja
+      - name: CMake Build
+        run: cmake --build cmake_build -j$(( ( $(nproc) + 1 ) / 2 ))
+      - name: Gather Test Binary and Input files
+        run: |
+          mkdir artifact
+          mv cmake_build/abacus_tests ./artifact
+      - name: Upload Test Binary Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: abacus_tests
+          path: artifact
+          retention-days: 1
+  tests:
+    needs: cross-compile
+    strategy:
+      fail-fast: false
+    runs-on: [self-hosted, raspberry_pi_4]
+    name: Run Tests on Raspberry Pi
+    steps:
+      - name: Checkout source code
+        uses: actions/checkout@v3
+      - name: Download Test Binary Artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: abacus_tests
+      - name: List files
+        run: ls -l
+      - name: Run all tests
+        run: chmod +x abacus_tests
+      - name: Get backtrace on failure if available
+        run: |
+          if ! ./abacus_tests; then
+            echo "Test failed, getting backtrace"
+            gdb -batch -ex "r" -ex "thread apply all backtrace full" -ex "quit" ./abacus_tests
+            exit 1
+          fi
+
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
   cancel-in-progress: true
